name: "prueba edt"
version: '0.1'
services:
  postgresdb:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - network1
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - network1
    depends_on:
      - postgresdb
    restart: always
    environment:
      - ENV=dev

networks:
  network1:
